### ISSUE TITLE
Problem with accessing other urls other than /info

### ISSUE THREAD

**Issue by testbautista** [Totonyus/ydl_api_ng#13]
The /active-downloads endpoint was working before now I have problems accessing it.

Here are the logs:

[11-10-23 15:06:00][uvicorn.access][INFO] {Internal IP}:5166 - "GET /queue HTTP/1.1" 500
[11-10-23 15:06:00][uvicorn.error][ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 291, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 179, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/site-packages/fastapi/encoders.py", line 195, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/site-packages/fastapi/encoders.py", line 209, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/site-packages/fastapi/encoders.py", line 195, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/site-packages/fastapi/encoders.py", line 195, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/site-packages/fastapi/encoders.py", line 195, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/site-packages/fastapi/encoders.py", line 224, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File "/usr/local/lib/python3.9/site-packages/fastapi/encoders.py", line 58, in <lambda>
    bytes: lambda o: o.decode(),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by Totonyus** [comment]
Hi.

Can you try to empty the finished downloads in the queue by using DELETE /queue ?

At least it will tell us if the server has a problem receiving the request of problem sending the answer.

Also what version are you using ? Docker version on last build ?
