### ISSUE TITLE
PostProcessing using _cli fails

### ISSUE THREAD

**Issue by Guyver111** [Totonyus/ydl_api_ng#25]
Hi and happy new year :)

I'm trying to get my yt-dlp config to work, using the "_cli" parameter.

When i try to use the yt-dlp config file:
`_cli = --config-location params/fb.conf`

i get a traceback error:
```
Traceback (most recent call last):
  File "/app/programmation_daemon.py", line 8, in <module>
    import programmation_persistence_manager
  File "/app/programmation_persistence_manager.py", line 3, in <module>
    from programmation_class import Programmation
  File "/app/programmation_class.py", line 8, in <module>
    __cm = config_manager.ConfigManager()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/config_manager.py", line 89, in __init__
    self.__dispatch_configs()
  File "/app/config_manager.py", line 126, in __dispatch_configs
    self.__presets_config[section] = self.__expand_config(section)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/config_manager.py", line 147, in __expand_config
    self.__expand_section(current_params, temp_config)
  File "/app/config_manager.py", line 168, in __expand_section
    self.__merge_configs(ydl_utils.cli_to_api(value), section, config_set)
  File "/app/config_manager.py", line 184, in __merge_configs
    dest[key] = json.dumps(value)
                ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```

When i add the yt-dlp config parameters directly:
`_cli = --trim-filenames 200 --no-mtime --use-postprocessor FFmpegCopyStream --ppa CopyStream:"-c:v libx264 -c:a aac -f mp4"`

i get the following error in the programmation.log:
`error during _cli expansion : error: wrong --ppa formatting; No closing quotation`

The download itself works but the postprecessing gets skipped.
I tried different quotations around the `CopyStream:"-c:v libx264 -c:a aac -f mp4"` but that didn't help.

Any idea how i can get the postprecessing to work and does the config file have to be in a specific format?

**Comment by Totonyus** [comment]
Hi !

> i get the following error in the programmation.log:
error during _cli expansion : error: wrong --ppa formatting; No closing quotation

I tried by using the test script provided by yt-dlp and it's an issue not related to ydl_api_ng.

I tried a lot of things but just cannot make it work.

So I tried with `_cli = --config-location params/fb.conf` and just cannot reproduce the error. It works fine for me.

Content of the file : 
Tried with : 
```
--trim-filenames 200 --no-mtime --use-postprocessor FFmpegCopyStream --ppa CopyStream:"-c:v libx264 -c:a aac -f mp4"
```

and

```
--trim-filenames 200 
--no-mtime 
--use-postprocessor FFmpegCopyStream 
--ppa CopyStream:"-c:v libx264 -c:a aac -f mp4"
```

Can you tell me the build date of the docker image you are using ? And can you give me the url to download ? I tried with a youtube video but I guess you try to dowload a facebook video. (It shouldn't change anything, presets expension is on serveur startup)

**Comment by Guyver111** [comment]
Hi,

thx for your quick reply.
And it appears i have to say sorry.

I tested again just now.
I still get the "error during _cli expansion : error: wrong --ppa formatting; No closing quotation", if i enter the parameters direktly in the "_cli" variable.

But after deleting the content of "params/fb.conf", copying the lines from your reply into it and restarting the docker container, it started to work.

Apparently i made a mistake when i copied (linux shell to linux shell) the content of the fb.conf from the old system.
